vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        picture_file:
            uri_prefix: /uploads/images/pictures
            upload_destination: '%upload_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        small_picture_file:
            uri_prefix: /uploads/images/pictures
            upload_destination: '%upload_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        book_file:
            upload_destination: '%kernel.project_dir%/private/uploads/books'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        annex_file:
            upload_destination: '%kernel.project_dir%/private/uploads/annex'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
